"""
Realistic mock data that mirrors the Odoo CRM schema used by CrmService.
50 leads, 5 teams, 8 salespeople, all stages referenced in config.
"""

from typing import Any

# ── Lookup tables ─────────────────────────────────────────────────────────────

STAGES: list[dict] = [
    {"id": 26, "name": "Closed Won"},
    {"id": 28, "name": "New Lead"},  # CRITICAL
    {"id": 30, "name": "Closed Lost"},
    {"id": 31, "name": "Closed Duplicate"},
    {"id": 32, "name": "Closed Invalid"},
    {"id": 34, "name": "Qualified"},  # CRITICAL
    {"id": 35, "name": "Proposal Sent"},  # CRITICAL
    {"id": 37, "name": "Negotiation"},  # CRITICAL
    {"id": 38, "name": "Closed No Answer"},
    {"id": 41, "name": "Contract Sent"},  # CRITICAL
    {"id": 42, "name": "Closed Cancelled"},
    {"id": 44, "name": "New X"},  # DATA_QUALITY
    {"id": 46, "name": "Closed Transferred"},
]

TEAMS: list[dict] = [
    {"id": 1, "name": "Alpha Team"},
    {"id": 2, "name": "Beta Team"},
    {"id": 3, "name": "Gamma Team"},
    {"id": 4, "name": "Delta Team"},
    {"id": 5, "name": "Epsilon Team"},
]

USERS: list[dict] = [
    {"id": 10, "name": "Ahmed Hassan"},
    {"id": 11, "name": "Sara Ibrahim"},
    {"id": 12, "name": "Mohamed Ali"},
    {"id": 13, "name": "Fatima Nour"},
    {"id": 14, "name": "Khaled Sayed"},
    {"id": 15, "name": "Layla Mahmoud"},
    {"id": 16, "name": "Omar Tarek"},
    {"id": 17, "name": "Nadia Saleh"},
]

SOURCES: list[dict] = [
    {"id": 1, "name": "Website"},
    {"id": 2, "name": "Phone Call"},
    {"id": 3, "name": "Referral"},
    {"id": 4, "name": "Email Campaign"},
]

# ── Helper lookups ────────────────────────────────────────────────────────────

_STAGE_MAP = {s["id"]: s["name"] for s in STAGES}
_TEAM_MAP = {t["id"]: t["name"] for t in TEAMS}
_USER_MAP = {u["id"]: u["name"] for u in USERS}
_SOURCE_MAP = {s["id"]: s["name"] for s in SOURCES}


def _t(tid: int) -> list:
    return [tid, _TEAM_MAP[tid]]


def _u(uid: int) -> list:
    return [uid, _USER_MAP[uid]]


def _s(sid: int) -> list:
    return [sid, _STAGE_MAP[sid]]


def _src(sid: int) -> list:
    return [sid, _SOURCE_MAP[sid]]


# ── Lead records ─────────────────────────────────────────────────────────────
# All leads are type=opportunity & opportunity_status=resolved.
# phone/mobile/phone_* = False means missing contact info.

LEADS: list[dict[str, Any]] = [
    # Overdue + critical stage (ids 28, 34, 35, 37, 41)
    {
        "id": 1,
        "name": "Sunset Villa",
        "contact_name": "Client A",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(28),
        "user_id": _u(10),
        "team_id": _t(1),
        "source_id": _src(1),
        "create_date": "2025-01-10 09:00:00",
        "phone": "+201001",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 2,
        "name": "Blue Tower",
        "contact_name": "Client B",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(34),
        "user_id": _u(11),
        "team_id": _t(1),
        "source_id": _src(2),
        "create_date": "2025-01-15 10:00:00",
        "phone": "+201002",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 3,
        "name": "Green Heights",
        "contact_name": "Client C",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(35),
        "user_id": _u(12),
        "team_id": _t(2),
        "source_id": _src(1),
        "create_date": "2025-02-01 08:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 4,
        "name": "Red Palm",
        "contact_name": "Client D",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(37),
        "user_id": _u(13),
        "team_id": _t(2),
        "source_id": _src(3),
        "create_date": "2025-02-10 09:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 5,
        "name": "Silver Oasis",
        "contact_name": "Client E",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(41),
        "user_id": _u(14),
        "team_id": _t(3),
        "source_id": _src(4),
        "create_date": "2025-02-20 11:00:00",
        "phone": "+201005",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # Overdue + non-critical stages
    {
        "id": 6,
        "name": "Golden Dunes",
        "contact_name": "Client F",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(34),
        "user_id": _u(15),
        "team_id": _t(3),
        "source_id": _src(1),
        "create_date": "2025-03-01 10:00:00",
        "phone": "+201006",
        "mobile": "+201106",
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 7,
        "name": "Crystal Bay",
        "contact_name": "Client G",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(35),
        "user_id": _u(16),
        "team_id": _t(4),
        "source_id": _src(2),
        "create_date": "2025-03-05 09:00:00",
        "phone": "+201007",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 8,
        "name": "Amber Park",
        "contact_name": "Client H",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(28),
        "user_id": _u(17),
        "team_id": _t(4),
        "source_id": _src(3),
        "create_date": "2025-03-10 10:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 9,
        "name": "Ivory Gate",
        "contact_name": "Client I",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(41),
        "user_id": _u(10),
        "team_id": _t(5),
        "source_id": _src(4),
        "create_date": "2025-03-15 11:00:00",
        "phone": "+201009",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 10,
        "name": "Pearl Heights",
        "contact_name": "Client J",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(37),
        "user_id": _u(11),
        "team_id": _t(5),
        "source_id": _src(1),
        "create_date": "2025-03-20 08:00:00",
        "phone": "+201010",
        "mobile": "+201110",
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # Planned follow-ups
    {
        "id": 11,
        "name": "Sunrise Tower",
        "contact_name": "Client K",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "planned",
        "stage_id": _s(34),
        "user_id": _u(12),
        "team_id": _t(1),
        "source_id": _src(2),
        "create_date": "2025-04-01 09:00:00",
        "phone": "+201011",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 12,
        "name": "Maple Grove",
        "contact_name": "Client L",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "planned",
        "stage_id": _s(35),
        "user_id": _u(13),
        "team_id": _t(2),
        "source_id": _src(3),
        "create_date": "2025-04-05 10:00:00",
        "phone": "+201012",
        "mobile": "+201112",
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 13,
        "name": "Olive Court",
        "contact_name": "Client M",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "planned",
        "stage_id": _s(37),
        "user_id": _u(14),
        "team_id": _t(3),
        "source_id": _src(4),
        "create_date": "2025-04-10 11:00:00",
        "phone": "+201013",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 14,
        "name": "Jasmine Valley",
        "contact_name": "Client N",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "planned",
        "stage_id": _s(41),
        "user_id": _u(15),
        "team_id": _t(4),
        "source_id": _src(1),
        "create_date": "2025-04-15 09:00:00",
        "phone": "+201014",
        "mobile": "+201114",
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 15,
        "name": "Cedarwood Estate",
        "contact_name": "Client O",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "planned",
        "stage_id": _s(28),
        "user_id": _u(16),
        "team_id": _t(5),
        "source_id": _src(2),
        "create_date": "2025-04-20 10:00:00",
        "phone": "+201015",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # Today follow-ups
    {
        "id": 16,
        "name": "Willow Springs",
        "contact_name": "Client P",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "today",
        "stage_id": _s(34),
        "user_id": _u(17),
        "team_id": _t(1),
        "source_id": _src(3),
        "create_date": "2025-05-01 09:00:00",
        "phone": "+201016",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 17,
        "name": "Harbor View",
        "contact_name": "Client Q",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "today",
        "stage_id": _s(35),
        "user_id": _u(10),
        "team_id": _t(2),
        "source_id": _src(4),
        "create_date": "2025-05-05 10:00:00",
        "phone": "+201017",
        "mobile": "+201117",
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 18,
        "name": "Eastgate Residences",
        "contact_name": "Client R",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "today",
        "stage_id": _s(41),
        "user_id": _u(11),
        "team_id": _t(3),
        "source_id": _src(1),
        "create_date": "2025-05-08 11:00:00",
        "phone": "+201018",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # No activity
    {
        "id": 19,
        "name": "Parkside Manor",
        "contact_name": "Client S",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": _s(34),
        "user_id": _u(12),
        "team_id": _t(4),
        "source_id": _src(2),
        "create_date": "2025-05-10 09:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 20,
        "name": "Skyline Lofts",
        "contact_name": "Client T",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": _s(35),
        "user_id": _u(13),
        "team_id": _t(5),
        "source_id": _src(3),
        "create_date": "2025-05-12 10:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 21,
        "name": "Desert Rose",
        "contact_name": "Client U",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": _s(41),
        "user_id": False,
        "team_id": _t(1),
        "source_id": _src(4),
        "create_date": "2025-05-14 11:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 22,
        "name": "Coral Springs",
        "contact_name": "Client V",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": _s(28),
        "user_id": False,
        "team_id": _t(2),
        "source_id": _src(1),
        "create_date": "2025-05-16 09:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # Data quality: missing stage
    {
        "id": 23,
        "name": "Unnamed Plot 1",
        "contact_name": "",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": False,
        "user_id": _u(14),
        "team_id": _t(3),
        "source_id": False,
        "create_date": "2025-05-18 10:00:00",
        "phone": "+201023",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 24,
        "name": "Unnamed Plot 2",
        "contact_name": "",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": False,
        "user_id": _u(15),
        "team_id": _t(4),
        "source_id": False,
        "create_date": "2025-05-19 09:00:00",
        "phone": "+201024",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # Data quality: New X stage (id 44)
    {
        "id": 25,
        "name": "New X Lead 1",
        "contact_name": "Client W",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": _s(44),
        "user_id": _u(16),
        "team_id": _t(5),
        "source_id": _src(2),
        "create_date": "2025-05-20 10:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 26,
        "name": "New X Lead 2",
        "contact_name": "Client X",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": False,
        "stage_id": _s(44),
        "user_id": _u(17),
        "team_id": _t(1),
        "source_id": _src(3),
        "create_date": "2025-05-21 11:00:00",
        "phone": False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # Closed/excluded stages (overdue here should NOT appear in followup risk)
    {
        "id": 27,
        "name": "Closed Deal A",
        "contact_name": "Client Y",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(26),
        "user_id": _u(10),
        "team_id": _t(1),
        "source_id": _src(1),
        "create_date": "2025-01-01 09:00:00",
        "phone": "+201027",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    {
        "id": 28,
        "name": "Closed Deal B",
        "contact_name": "Client Z",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": "overdue",
        "stage_id": _s(30),
        "user_id": _u(11),
        "team_id": _t(2),
        "source_id": _src(2),
        "create_date": "2025-01-05 10:00:00",
        "phone": "+201028",
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    },
    # More planned/no-activity to reach 50 total
] + [
    {
        "id": 29 + i,
        "name": f"Property Unit {29 + i}",
        "contact_name": f"Client {29 + i}",
        "type": "opportunity",
        "opportunity_status": "resolved",
        "activity_state": ["planned", False, "overdue"][i % 3],
        "stage_id": _s([34, 35, 37, 41, 28][i % 5]),
        "user_id": _u(10 + (i % 8)),
        "team_id": _t(1 + (i % 5)),
        "source_id": _src(1 + (i % 4)),
        "create_date": f"2025-0{(i % 9) + 1}-{(i % 28) + 1:02d} 09:00:00",
        "phone": f"+20100{29 + i}" if i % 3 != 0 else False,
        "mobile": False,
        "phone_one": False,
        "phone_two": False,
        "phone_three": False,
        "phone_four": False,
        "phone_five": False,
        "phone_six": False,
        "phone_seven": False,
        "phone_eight": False,
        "phone_nine": False,
        "phone_ten": False,
        "phone_note_ids": False,
    }
    for i in range(22)  # leads 29..50
]
